# Generated by Django 4.1.5 on 2023-10-09 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code_name', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code_name', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=models.SET(1), to='err_notif_conf.status')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code_name', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=300)),
                ('message_text', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=models.SET(1), to='err_notif_conf.status')),
                ('type', models.ForeignKey(on_delete=models.SET(1), to='err_notif_conf.errortype')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=models.SET(1), to='err_notif_conf.status')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('default_value_name', models.CharField(max_length=150)),
                ('code_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=400)),
                ('value', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=models.SET(1), to='err_notif_conf.status')),
                ('type', models.ForeignKey(on_delete=models.SET(1), to='err_notif_conf.configurationtype')),
            ],
        ),
    ]
