# Generated by Django 4.1.5 on 2023-10-09 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(max_length=75, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_1', models.CharField(max_length=500)),
                ('body_2', models.CharField(blank=True, max_length=500)),
                ('body_3', models.CharField(blank=True, max_length=500)),
                ('from_email', models.EmailField(default='pediahome@pediahome.com', max_length=254)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
